[package]
name = "rs-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.16"
pathfinding = "4.3.0"
serde_json = "1.0"
